name: Build on PR

on:
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['16.x']

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install packages
        run: npm ci
      
      - name: Output npm error log if npm ci fails
        if: failure()
        run: cat /home/runner/.npm/_logs/*-debug.log

      - name: Run npm build
        run: npm run build
