name: Build & Deploy

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['16.x']

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install packages
        run: npm ci

      - name: Run npm build
        run: npm run build:prod

      - name: Print current working directory
        run: pwd

      - name: List current working directory
        run: ls -la

      - name: List build directory
        run: ls -la _site

      - name: List hidden files in build directory
        run: ls -la _site/.*

      - name: Copy build files to temp directory
        run: cp -R _site/* _site/.* /tmp/deploy

      - name: List temp directory
        run: ls -la /tmp/deploy

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: /tmp/deploy
